menu:
- {name: 'About',    url: 'about.html'}
- {name: 'Research', url: 'research.html'}

social:
- {icon: 'github',     link: 'https://github.com/zhengwuma'}
- {icon: 'twitter',    link: 'https://twitter.com/zhengwuma'}
- {icon: 'graduation-cap',  link: 'https://scholar.google.com/citations?user=AFkl-oQAAAAJ&hl=en&oi=ao'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/zhengwu-ma/'}
- {icon: 'envelope',   link: 'mailto:zhengwu.ma@my.cityu.edu.hk'}
