# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ' '

menu:
- {name: 'About',    url: 'about.html'}
- {name: 'Research', url: 'research.html'}
- {name: 'Gallery',  url: 'gallery.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/zhengwuma'}
- {icon: 'google-scholar',  link: 'https://scholar.google.com/citations?user=AFkl-oQAAAAJ&hl=en&oi=ao'}
- {icon: 'twitter',    link: 'https://twitter.com/zhengwuma'}
- {icon: 'instagram',   link: 'https://www.instagram.com/zhengwu_ma/'}
- {icon: 'envelope',   link: 'mailto:zhengwuma2-c@my.cityu.edu.hk'}

# Customize site text
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'
